### ISSUE TITLE
Go 1.21.1 build WASM is broken

### ISSUE THREAD

**Issue by justgook** [mcarpenter622/ebitenui#93]
## Steps to reproduce:
1. install go 1.21.1
2. run `GOOS=js GOARCH=wasm go build -o ./game.wasm ./_examples/widget_demos/anchorlayout/main.go`
3. run in web (copy wasm_exec.js, build index.html)

## Expected result:
no errors all runs smoothly 

## Real result
got error:
```panic: syscall/js: call of Value.Get on undefined
wasm_exec.js:22 
wasm_exec.js:22 goroutine 1 [running]:
wasm_exec.js:22 syscall/js.Value.Get({{}, 0x0, 0x0}, {0x94b21, 0x9})
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.21.1/libexec/src/syscall/js/js.go:290 +0xc
wasm_exec.js:22 github.com/ebitenui/ebitenui/internal/jsUtil.init.0()
wasm_exec.js:22 	/Users/gook/Repos/ebitenui/internal/jsUtil/util_js.go:36 +0xf
wasm_exec.js:101 exit code: 2
exit @ wasm_exec.js:101
runtime.wasmExit @ wasm_exec.js:232
$runtime.wasmExit @ 02639246:0xe100d
$runtime.exit @ 02639246:0x10c748
$runtime.fatalpanic.func2 @ 02639246:0xfde99
$runtime.systemstack @ 02639246:0x109e8d
$runtime.fatalpanic @ 02639246:0x9a1ef
$runtime.gopanic @ 02639246:0x989ae
$syscall_js.Value.Get @ 02639246:0x1b7712
$github.com_ebitenui_ebitenui_internal_jsUtil.init.0 @ 02639246:0x581c2b
$runtime.doInit1 @ 02639246:0xc1aad
$wasm_pc_f_loop @ 02639246:0x10c63e
$wasm_export_run @ 02639246:0x10c6ff
run @ wasm_exec.js:534
(anonymous) @ (index):37
Promise.then (async)
(anonymous) @ (index):36
```

## Notes:
1. Ebitengine compiles without problems
2. go1.20.8 - compiles
3. go1.21.0 - **NOT** compiles

**Comment by justgook** [comment]
Found The issue: 
there is race condition in JS part (try access canvas before it exists):
https://github.com/ebitenui/ebitenui/blob/42a459536e3db19fe3cc9ec9af2924ac5a3a982a/internal/jsUtil/util_js.go#L35

To fix it wrap that part with requestAnimationFrame:
```go
	requestAnimationFrame := js.Global().Get("requestAnimationFrame")
	requestAnimationFrame.Invoke(js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		//Get the canvas and attach an event listener for screen touches
		canvas := document.Get("body").Call("getElementsByTagName", "canvas").Index(0)
		offsetTop = canvas.Get("offsetTop").Int()
		canvas.Call("addEventListener", "touchstart", js.FuncOf(handleClick), false)
		canvas.Call("addEventListener", "touchend", js.FuncOf(handleClick), false)
		return nil
	}))
```

**Comment by quasilyte** [comment]
It looks like I have the same issue.

ebitenui + go1.21 doesn't work in wasm.
ebitenui + go1.20 does work.

![image](https://github.com/ebitenui/ebitenui/assets/6286655/f83a6b24-7691-4f77-8bce-511fe4e3a2bd)

**Comment by mcarpenter622** [comment]
Good to know! I'll test the fix out in a few minutes.

**Comment by justgook** [comment]
need PR?

**Comment by pedronasser** [comment]
To be honest a lot of stuff on go1.21 wasm is broken. I suggest not using 1.21 until 1.22 is released.

**Comment by mcarpenter622** [comment]
Should be good now
